{% set name = "mistletoe" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mistletoe-{{ version }}.tar.gz
  sha256: 3ad979a94207792456573604f57df36a22fb1a4c81d7f9d1b9f3eca88608a0ab

build:
  entry_points:
    - mistletoe = mistletoe.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - mistletoe
  commands:
    - pip check
    - mistletoe --help
  requires:
    - pip

about:
  home: https://github.com/miyuchina/mistletoe
  summary: A fast, extensible Markdown parser in pure Python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - domdfcoding
