{% set name = "mistletoe" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mistletoe-{{ version }}.tar.gz
  sha256: 1630f906e5e4bbe66fdeb4d29d277e2ea515d642bb18a9b49b136361a9818c9d

build:
  entry_points:
    - mistletoe = mistletoe.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - mistletoe
  commands:
    - pip check
    - mistletoe --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/miyuchina/mistletoe
  summary: A fast, extensible Markdown parser in pure Python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - domdfcoding
